# typed: false
# frozen_string_literal: true

# Homebrew formula for pi-run — the pi-harness CLI.
# Installs the prebuilt binary for the user's platform from the GitHub release.
# NOTE: generated by scripts/update-homebrew-formula.sh — do not edit by hand.
class PiRun < Formula
  desc "Provider-agnostic coding-agent harness CLI (Pi + DeepEval)"
  homepage "https://github.com/forrestbthomas/pi-harness"
  version "v0.4.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/forrestbthomas/pi-harness/releases/download/v0.4.3/pi-run-darwin-arm64"
      sha256 "8d63dc5c92afae913fe998f41a7e229588caeaa320a4486e1464b46794a03c79"

      def install
        bin.install "pi-run-darwin-arm64" => "pi-run"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/forrestbthomas/pi-harness/releases/download/v0.4.3/pi-run-darwin-amd64"
      sha256 "d734e918ba3405bcb7468c59b50ecb87437691f48a173a2d7276a3a4e3fe3f73"

      def install
        bin.install "pi-run-darwin-amd64" => "pi-run"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/forrestbthomas/pi-harness/releases/download/v0.4.3/pi-run-linux-arm64"
      sha256 "690f4ee7f360820d0c5d9e32af3c3a1bb274c63913f7bbe150d6c8876ed58160"

      def install
        bin.install "pi-run-linux-arm64" => "pi-run"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/forrestbthomas/pi-harness/releases/download/v0.4.3/pi-run-linux-amd64"
      sha256 "360c4e5720f82a0122353e988a918950bea546e5c4b73aebc382db2ece40b998"

      def install
        bin.install "pi-run-linux-amd64" => "pi-run"
      end
    end
  end

  test do
    system "#{bin}/pi-run", "version"
  end
end
