# typed: false
# frozen_string_literal: true

# Homebrew formula for pi-run — the pi-harness CLI.
# Installs the prebuilt binary for the user's platform from the GitHub release.
# NOTE: generated by scripts/update-homebrew-formula.sh — do not edit by hand.
class PiRun < Formula
  desc "Provider-agnostic coding-agent harness CLI (Pi + DeepEval)"
  homepage "https://github.com/forrestbthomas/pi-harness"
  version "v0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/forrestbthomas/pi-harness/releases/download/v0.4.1/pi-run-darwin-arm64"
      sha256 "9becdd152f105f52c53000abbdd5edff8b280ef7029c13d3f9d79066e0da5e66"

      def install
        bin.install "pi-run-darwin-arm64" => "pi-run"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/forrestbthomas/pi-harness/releases/download/v0.4.1/pi-run-darwin-amd64"
      sha256 "fa18fa1b7dbfc7d842baa0899b2d11ef4289597390a69e7ed19c85cfa42ace24"

      def install
        bin.install "pi-run-darwin-amd64" => "pi-run"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/forrestbthomas/pi-harness/releases/download/v0.4.1/pi-run-linux-arm64"
      sha256 "c4bf5b1a339f1a38ce97c64f0ee8f3212a50d3da80d1d0910b18e627010a11ce"

      def install
        bin.install "pi-run-linux-arm64" => "pi-run"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/forrestbthomas/pi-harness/releases/download/v0.4.1/pi-run-linux-amd64"
      sha256 "35db85d4260d2927a2105ab585f73b8d7c7b2f128bb7e77eaa6a48cb9e470355"

      def install
        bin.install "pi-run-linux-amd64" => "pi-run"
      end
    end
  end

  test do
    system "#{bin}/pi-run", "version"
  end
end
