# typed: false
# frozen_string_literal: true

# Homebrew formula for pi-run — the pi-harness CLI.
# Installs the prebuilt binary for the user's platform from the GitHub release.
# NOTE: generated by scripts/update-homebrew-formula.sh — do not edit by hand.
class PiRun < Formula
  desc "Provider-agnostic coding-agent harness CLI (Pi + DeepEval)"
  homepage "https://github.com/forrestbthomas/pi-harness"
  version "v0.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/forrestbthomas/pi-harness/releases/download/v0.10.0/pi-run-darwin-arm64"
      sha256 "b0cf3fd8048ff2a8272bf1864dc3b92f06d9b9cdfd31da16e33db72b94dac9de"

      def install
        bin.install "pi-run-darwin-arm64" => "pi-run"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/forrestbthomas/pi-harness/releases/download/v0.10.0/pi-run-darwin-amd64"
      sha256 "716f084351dd835a87760988bed803416ead4c04a42914ca02fa7ceaa2965ac0"

      def install
        bin.install "pi-run-darwin-amd64" => "pi-run"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/forrestbthomas/pi-harness/releases/download/v0.10.0/pi-run-linux-arm64"
      sha256 "9587d2bab6d6e788d34ed1a5ed54dd5275287b86bec043d9f1bcfca7ce7e1e96"

      def install
        bin.install "pi-run-linux-arm64" => "pi-run"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/forrestbthomas/pi-harness/releases/download/v0.10.0/pi-run-linux-amd64"
      sha256 "900a2a68bcbb845b29d1b7b52bef4def98585f1e4aafdebc46a0ba73e30ca8f7"

      def install
        bin.install "pi-run-linux-amd64" => "pi-run"
      end
    end
  end

  test do
    system "#{bin}/pi-run", "version"
  end
end
